use std::path::PathBuf;

use maya_scene_kit::{
    check_script_nodes, convert_to_maya_ascii, dump_requires, dump_script_nodes, parse_file,
    remove_script_nodes,
};
use tempfile::tempdir;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn script_check_ma() {
    let report = check_script_nodes(repo_root().join("tests/02/sphere.ma")).unwrap();
    assert_eq!(report.scene_format, "ma");
    assert!(report.count() >= 2);
    assert!(
        report
            .nodes
            .iter()
            .any(|n| n == "uiConfigurationScriptNode")
    );
    assert!(
        report
            .nodes
            .iter()
            .any(|n| n == "sceneConfigurationScriptNode")
    );
}

#[test]
fn script_clean_ma() {
    let source = repo_root().join("tests/02/sphere.ma");
    let dir = tempdir().unwrap();
    let output = dir.path().join("sphere_clean.ma");
    let result = remove_script_nodes(&source, &output).unwrap();
    assert_eq!(result.scene_format, "ma");
    assert!(result.removed_count() >= 2);

    let report = check_script_nodes(&output).unwrap();
    assert_eq!(report.count(), 0);
    assert!(
        std::fs::read_to_string(&output)
            .unwrap()
            .contains("createNode mesh -n \"pSphereShape1\"")
    );
}

#[test]
fn script_check_and_clean_mb() {
    let source = repo_root().join("tests/02/sphere.mb");
    let original_report = check_script_nodes(&source).unwrap();
    assert_eq!(original_report.scene_format, "mb");
    assert!(original_report.count() > 0);

    let dir = tempdir().unwrap();
    let output = dir.path().join("sphere_clean.mb");
    let result = remove_script_nodes(&source, &output).unwrap();
    assert_eq!(result.scene_format, "mb");
    assert_eq!(result.removed_count(), original_report.count());

    let cleaned_report = check_script_nodes(&output).unwrap();
    assert_eq!(cleaned_report.count(), 0);

    let parsed = parse_file(&output).unwrap();
    assert!(
        !parsed
            .root
            .children
            .iter()
            .any(|child| child.form_type.as_deref() == Some("SCRP"))
    );
}

#[test]
fn script_dump_ma() {
    let source = repo_root().join("tests/02/sphere.ma");
    let dir = tempdir().unwrap();
    let output = dir.path().join("script_dump.txt");

    let result = dump_script_nodes(&source, &output).unwrap();
    assert_eq!(result.scene_format, "ma");
    assert!(result.dumped_count() >= 2);
    assert!(
        result
            .dumped_nodes
            .iter()
            .any(|n| n == "uiConfigurationScriptNode")
    );

    let text = std::fs::read_to_string(output).unwrap();
    assert!(text.contains("# maya-scene-kit Script Node Dump"));
    assert!(text.contains("uiConfigurationScriptNode"));
}

#[test]
fn requires_dump_mb() {
    let source = repo_root().join("tests/02/sphere.mb");
    let dir = tempdir().unwrap();
    let output = dir.path().join("requires_dump.txt");

    let result = dump_requires(&source, &output).unwrap();
    assert_eq!(result.scene_format, "mb");
    assert!(result.dumped_count() >= 1);
    assert!(
        result
            .requires
            .iter()
            .any(|r| r.starts_with("requires maya "))
    );

    let text = std::fs::read_to_string(output).unwrap();
    assert!(text.contains("# maya-scene-kit Requires Dump"));
    assert!(text.contains("requires maya \""));
}

#[test]
fn convert_to_ascii_from_mb_best_effort() {
    let source = repo_root().join("tests/02/sphere.mb");
    let dir = tempdir().unwrap();
    let output = dir.path().join("sphere.ma");
    let converted = convert_to_maya_ascii(&source, &output, false).unwrap();
    assert_eq!(converted, output);

    let text = std::fs::read_to_string(output).unwrap();
    assert!(text.contains("//Generated by MayaBinReader best-effort converter."));
    assert!(text.contains("createNode transform -s -n \"persp\";"));
    assert!(text.contains("createNode script -n \"uiConfigurationScriptNode\";"));
    assert!(text.contains("setAttr \".t\" -type \"double3\" 28 21 28 ;"));
    assert!(text.contains("setAttr \".imn\" -type \"string\" \"persp\";"));
    assert!(text.contains("setAttr \".st\" 3;"));
    assert!(text.contains("rename -uid \"97D44983-42C6-68B1-0C0B-6CA5DEEBF0CD\";"));
    assert!(text.contains("select -ne :defaultRenderGlobals;"));
    assert!(text.contains(
        "addAttr -ci true -h true -sn \"dss\" -ln \"defaultSurfaceShader\" -dt \"string\";"
    ));
    assert!(text.contains("connectAttr \"polySphere1.out\" \"pSphereShape1.i\";"));
    assert!(text.contains(
        "relationship \"shadowLink\" \":lightLinker1\" \":initialShadingGroup.message\" \":defaultLightSet.message\";"
    ));
}
