use std::{
    collections::{HashMap, HashSet},
    path::Path,
};

use maya_scene_kit_observe::scene::model::{
    RecoveredAttrOp, RecoveredHeader, RecoveredNode, SceneModel, SetAttrValue,
};
use maya_scene_kit_observe::scene::recovery::AngularAttrKind;

use super::{
    add_attr::render_add_attr_op,
    create::{render_link_op, render_select_block},
    format::escape_ma_string,
    refedit::format_reference_edits_setattr_from_data,
    references::render_reference_file_ops,
    set_attr::{SetAttrRenderContext, render_set_attr_op_with_render_context},
    units::{build_angular_render_unit, build_time_render_context},
};
use crate::mb::MbRequiresEntry;

pub(in crate::scene) fn render_best_effort_maya_ascii(
    metadata: &RecoveredHeader,
    scene_model: &SceneModel,
    source_path: &Path,
    output_name: &str,
    node_angular_attrs: &HashMap<String, HashMap<String, AngularAttrKind>>,
    embed_metadata: bool,
) -> String {
    let time_render_context = build_time_render_context(metadata);
    let angular_render_unit = build_angular_render_unit(metadata);

    let vers = metadata.maya_version();

    let mut lines = vec![
        format!("//Maya ASCII {vers} scene"),
        format!("//Name: {output_name}"),
    ];
    if embed_metadata {
        lines.push(format!("//Source: {}", source_path.display()));
    }
    lines.push("//Generated by maya-scene-kit best-effort converter.".to_string());
    lines.push("//WARNING: This file may be incomplete or invalid for Maya load.".to_string());

    if let Some(chng) = &metadata.chng {
        lines.push(format!("//Source CHNG: {chng}"));
    }

    lines.push(String::new());
    lines.push(render_maya_requires(vers));

    let mut seen = HashSet::new();
    seen.insert(render_maya_requires(vers));
    for req in &metadata.requires {
        let rendered = render_requires_entry(req);
        if seen.insert(rendered.clone()) {
            lines.push(rendered);
        }
    }

    if !scene_model.reference_files.is_empty() {
        // FREF recovery preserves encounter order from the MB sections, but Maya ASCII writes
        // scene-level reference commands in a different normalized order: all `file -rdi`
        // records first in reference-tree preorder, then the top-level `file -r -dr 1` lines.
        lines.extend(render_reference_file_ops(&scene_model.reference_files));
    }

    lines.push(format!(
        "currentUnit -l {} -a {} -t {};",
        metadata.linear_unit(),
        metadata.angular_unit(),
        metadata.time_unit()
    ));

    for (key, value) in &metadata.file_info {
        lines.push(format!(
            "fileInfo \"{}\" \"{}\";",
            escape_ma_string(key),
            escape_ma_string(value)
        ));
    }
    lines.push(String::new());

    lines.push("//Recovered nodes/attributes from .mb chunks (best effort).".to_string());

    for node in &scene_model.nodes {
        let set_attr_render_context = SetAttrRenderContext {
            time_render_context: time_render_context.as_ref(),
            angular_render_unit,
            angular_attrs: node_angular_attrs.get(&node.name),
        };
        let shared_part = if node.create_flags.shared.is_true() {
            " -s"
        } else {
            ""
        };
        let skip_select_part = if node.create_flags.skip_select.is_true() {
            " -ss"
        } else {
            ""
        };
        let parent_part = node
            .parent
            .as_ref()
            .map(|parent| format!(" -p \"{}\"", escape_ma_string(parent)))
            .unwrap_or_default();
        lines.push(format!(
            "createNode {}{}{} -n \"{}\"{};",
            node.node_type,
            shared_part,
            skip_select_part,
            escape_ma_string(&node.name),
            parent_part
        ));
        if let Some(uid) = &node.uid {
            lines.push(format!("\trename -uid \"{uid}\";"));
        }
        for attr in &node.attrs {
            match attr {
                RecoveredAttrOp::AddAttr(op) => {
                    if let Some(add_attr) = render_add_attr_op(op) {
                        lines.push(format!("\t{add_attr}"));
                    }
                }
                RecoveredAttrOp::SetAttr(op) => lines.push(format!(
                    "\t{}",
                    render_set_attr_op_with_render_context(op, set_attr_render_context)
                )),
                RecoveredAttrOp::RefEdit { attr_name, data } => {
                    let cmd = format_reference_edits_setattr_from_data(&attr_path(attr_name), data);
                    for line in cmd.lines() {
                        lines.push(format!("\t{line}"));
                    }
                }
            }
        }
        for note in &node.decode_notes {
            lines.push(format!("\t//decode-note: {}", note.to_decode_note()));
        }
        if node.node_type.as_ref() == "script" && distinct_script_bodies(node).len() > 1 {
            lines.push(
                "\t//decode-note: inferred attr=.b reason=multiple divergent script bodies recovered for this script node".to_string(),
            );
        }
        lines.push(String::new());
    }

    if scene_model.nodes.is_empty() {
        lines.push("//No node stubs recovered.".to_string());
    }

    lines.push("//Recovered select blocks from SLCT chunks (best effort).".to_string());
    if scene_model.select_blocks.is_empty() {
        lines.push("//No SLCT blocks recovered.".to_string());
    } else {
        for block in &scene_model.select_blocks {
            lines.extend(render_select_block(
                block,
                time_render_context.as_ref(),
                angular_render_unit,
                node_angular_attrs,
            ));
        }
    }
    lines.push(String::new());

    lines.push("//Recovered links from CONS chunks (best effort).".to_string());
    if scene_model.links.is_empty() {
        lines.push("//No links recovered.".to_string());
    } else {
        lines.extend(scene_model.links.iter().map(render_link_op));
    }
    lines.push(String::new());

    lines.push("//End of best-effort conversion output.".to_string());
    lines.join("\n") + "\n"
}

fn render_maya_requires(version: &str) -> String {
    format!("requires maya \"{}\";", escape_ma_string(version))
}

fn render_requires_entry(entry: &MbRequiresEntry) -> String {
    let options_part = entry
        .options
        .as_deref()
        .map(|value| format!(" {value}"))
        .unwrap_or_default();
    format!(
        "requires{options_part} \"{}\" \"{}\";",
        escape_ma_string(&entry.plugin_name),
        escape_ma_string(&entry.version)
    )
}

fn attr_path(attr_name: &str) -> String {
    if attr_name.starts_with('.') {
        attr_name.to_string()
    } else {
        format!(".{attr_name}")
    }
}

fn distinct_script_bodies(node: &RecoveredNode) -> Vec<&str> {
    let mut bodies = Vec::new();
    for attr in &node.attrs {
        let RecoveredAttrOp::SetAttr(op) = attr else {
            continue;
        };
        if op.attr_name_or_path != ".b" {
            continue;
        }
        let SetAttrValue::String(body) = &op.value else {
            continue;
        };
        if !bodies.iter().any(|existing| existing == &body.as_str()) {
            bodies.push(body.as_str());
        }
    }
    bodies
}
